server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    # A server should not register with itself
    register-with-eureka: false
    # It also doesn't need to fetch the registry (since it IS the registry)
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
